backend:
    name: git-gateway
    branch: shop # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "static/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/uploads"

collections:
    - name: "product"
      label: "product"
      folder: "src/content/products"
      create: true
      slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
      fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Publish Date", name: "date", widget: "datetime", required: false}
        - {label: "Price", name: "price", widget: "number",  step: 0.01}
        - {label: "Description", name: "description", widget: "markdown", required: false}
        - {label: "Featured Image", name: "featured-image", widget: "image", comment: "Supported file formats: png"}
        - {label: "Extra images", name: "extra-images", widget: "list", summary: '{{fields.image}}', field: {label: "Extra image", name: "extra-image", widget: image}, required: false }
    - name: "sketch" # Used in routes, e.g., /admin/collections/blog
      label: "Sketch" # Used in the UI
      folder: "src/content/works" # The path to the folder where the documents are stored
      create: true # Allow users to create new documents in this collection
      slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
      fields: # The fields for each document, usually in front matter
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Publish Date", name: "date", widget: "datetime"}
        - {label: "Description", name: "description", widget: "string", required: false}
        - {label: "Featured Image", name: "image", widget: "image", comment: "Supported file formats: png"}
        - {label: "Github Link", name: "github", widget: "string", required: false}
        - {label: "Live url", name: "url", widget: "string", required: false}
        - {label: "Body", name: "body", widget: "markdown", required: false}
    - label: "Pages"
      name: "pages"
      files:
        - label: "Home page"
          name: "home"
          file: "src/content/pages/home.yml"
          fields:
            - {label: "Featured Image", name: "image", widget: "image"}
            - {label: Title, name: title, widget: string, required: false}
            - {label: Intro, name: intro, widget: markdown, required: false}
        - label: "About Page"
          name: "about"
          file: "src/content/pages/about.yml"
          fields:
            - {label: About, name: about, widget: markdown, required: false}